# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /macierz/home/137252ba/projekty/divide-conquer-framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /macierz/home/137252ba/projekty/divide-conquer-framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /macierz/home/137252ba/projekty/divide-conquer-framework/CMakeFiles /macierz/home/137252ba/projekty/divide-conquer-framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /macierz/home/137252ba/projekty/divide-conquer-framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named divide_conquer_framework

# Build rule for target.
divide_conquer_framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 divide_conquer_framework
.PHONY : divide_conquer_framework

# fast build rule for target.
divide_conquer_framework/fast:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/build
.PHONY : divide_conquer_framework/fast

framework/AbstractProblemSolver.o: framework/AbstractProblemSolver.cpp.o
.PHONY : framework/AbstractProblemSolver.o

# target to build an object file
framework/AbstractProblemSolver.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/AbstractProblemSolver.cpp.o
.PHONY : framework/AbstractProblemSolver.cpp.o

framework/AbstractProblemSolver.i: framework/AbstractProblemSolver.cpp.i
.PHONY : framework/AbstractProblemSolver.i

# target to preprocess a source file
framework/AbstractProblemSolver.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/AbstractProblemSolver.cpp.i
.PHONY : framework/AbstractProblemSolver.cpp.i

framework/AbstractProblemSolver.s: framework/AbstractProblemSolver.cpp.s
.PHONY : framework/AbstractProblemSolver.s

# target to generate assembly for a file
framework/AbstractProblemSolver.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/AbstractProblemSolver.cpp.s
.PHONY : framework/AbstractProblemSolver.cpp.s

framework/BaseProblemSolver.o: framework/BaseProblemSolver.cpp.o
.PHONY : framework/BaseProblemSolver.o

# target to build an object file
framework/BaseProblemSolver.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/BaseProblemSolver.cpp.o
.PHONY : framework/BaseProblemSolver.cpp.o

framework/BaseProblemSolver.i: framework/BaseProblemSolver.cpp.i
.PHONY : framework/BaseProblemSolver.i

# target to preprocess a source file
framework/BaseProblemSolver.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/BaseProblemSolver.cpp.i
.PHONY : framework/BaseProblemSolver.cpp.i

framework/BaseProblemSolver.s: framework/BaseProblemSolver.cpp.s
.PHONY : framework/BaseProblemSolver.s

# target to generate assembly for a file
framework/BaseProblemSolver.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/BaseProblemSolver.cpp.s
.PHONY : framework/BaseProblemSolver.cpp.s

framework/Framework.o: framework/Framework.cpp.o
.PHONY : framework/Framework.o

# target to build an object file
framework/Framework.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/Framework.cpp.o
.PHONY : framework/Framework.cpp.o

framework/Framework.i: framework/Framework.cpp.i
.PHONY : framework/Framework.i

# target to preprocess a source file
framework/Framework.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/Framework.cpp.i
.PHONY : framework/Framework.cpp.i

framework/Framework.s: framework/Framework.cpp.s
.PHONY : framework/Framework.s

# target to generate assembly for a file
framework/Framework.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/Framework.cpp.s
.PHONY : framework/Framework.cpp.s

framework/OmpLock.o: framework/OmpLock.cpp.o
.PHONY : framework/OmpLock.o

# target to build an object file
framework/OmpLock.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/OmpLock.cpp.o
.PHONY : framework/OmpLock.cpp.o

framework/OmpLock.i: framework/OmpLock.cpp.i
.PHONY : framework/OmpLock.i

# target to preprocess a source file
framework/OmpLock.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/OmpLock.cpp.i
.PHONY : framework/OmpLock.cpp.i

framework/OmpLock.s: framework/OmpLock.cpp.s
.PHONY : framework/OmpLock.s

# target to generate assembly for a file
framework/OmpLock.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/OmpLock.cpp.s
.PHONY : framework/OmpLock.cpp.s

framework/RandomBucketAccessor.o: framework/RandomBucketAccessor.cpp.o
.PHONY : framework/RandomBucketAccessor.o

# target to build an object file
framework/RandomBucketAccessor.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/RandomBucketAccessor.cpp.o
.PHONY : framework/RandomBucketAccessor.cpp.o

framework/RandomBucketAccessor.i: framework/RandomBucketAccessor.cpp.i
.PHONY : framework/RandomBucketAccessor.i

# target to preprocess a source file
framework/RandomBucketAccessor.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/RandomBucketAccessor.cpp.i
.PHONY : framework/RandomBucketAccessor.cpp.i

framework/RandomBucketAccessor.s: framework/RandomBucketAccessor.cpp.s
.PHONY : framework/RandomBucketAccessor.s

# target to generate assembly for a file
framework/RandomBucketAccessor.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/RandomBucketAccessor.cpp.s
.PHONY : framework/RandomBucketAccessor.cpp.s

framework/SharedQueue.o: framework/SharedQueue.cpp.o
.PHONY : framework/SharedQueue.o

# target to build an object file
framework/SharedQueue.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/SharedQueue.cpp.o
.PHONY : framework/SharedQueue.cpp.o

framework/SharedQueue.i: framework/SharedQueue.cpp.i
.PHONY : framework/SharedQueue.i

# target to preprocess a source file
framework/SharedQueue.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/SharedQueue.cpp.i
.PHONY : framework/SharedQueue.cpp.i

framework/SharedQueue.s: framework/SharedQueue.cpp.s
.PHONY : framework/SharedQueue.s

# target to generate assembly for a file
framework/SharedQueue.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/SharedQueue.cpp.s
.PHONY : framework/SharedQueue.cpp.s

framework/ThreadStats.o: framework/ThreadStats.cpp.o
.PHONY : framework/ThreadStats.o

# target to build an object file
framework/ThreadStats.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadStats.cpp.o
.PHONY : framework/ThreadStats.cpp.o

framework/ThreadStats.i: framework/ThreadStats.cpp.i
.PHONY : framework/ThreadStats.i

# target to preprocess a source file
framework/ThreadStats.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadStats.cpp.i
.PHONY : framework/ThreadStats.cpp.i

framework/ThreadStats.s: framework/ThreadStats.cpp.s
.PHONY : framework/ThreadStats.s

# target to generate assembly for a file
framework/ThreadStats.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadStats.cpp.s
.PHONY : framework/ThreadStats.cpp.s

framework/ThreadUnsafeLockFreeFactory.o: framework/ThreadUnsafeLockFreeFactory.cpp.o
.PHONY : framework/ThreadUnsafeLockFreeFactory.o

# target to build an object file
framework/ThreadUnsafeLockFreeFactory.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadUnsafeLockFreeFactory.cpp.o
.PHONY : framework/ThreadUnsafeLockFreeFactory.cpp.o

framework/ThreadUnsafeLockFreeFactory.i: framework/ThreadUnsafeLockFreeFactory.cpp.i
.PHONY : framework/ThreadUnsafeLockFreeFactory.i

# target to preprocess a source file
framework/ThreadUnsafeLockFreeFactory.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadUnsafeLockFreeFactory.cpp.i
.PHONY : framework/ThreadUnsafeLockFreeFactory.cpp.i

framework/ThreadUnsafeLockFreeFactory.s: framework/ThreadUnsafeLockFreeFactory.cpp.s
.PHONY : framework/ThreadUnsafeLockFreeFactory.s

# target to generate assembly for a file
framework/ThreadUnsafeLockFreeFactory.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadUnsafeLockFreeFactory.cpp.s
.PHONY : framework/ThreadUnsafeLockFreeFactory.cpp.s

framework/ThreadUnsafeLockFreeQueue.o: framework/ThreadUnsafeLockFreeQueue.cpp.o
.PHONY : framework/ThreadUnsafeLockFreeQueue.o

# target to build an object file
framework/ThreadUnsafeLockFreeQueue.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadUnsafeLockFreeQueue.cpp.o
.PHONY : framework/ThreadUnsafeLockFreeQueue.cpp.o

framework/ThreadUnsafeLockFreeQueue.i: framework/ThreadUnsafeLockFreeQueue.cpp.i
.PHONY : framework/ThreadUnsafeLockFreeQueue.i

# target to preprocess a source file
framework/ThreadUnsafeLockFreeQueue.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadUnsafeLockFreeQueue.cpp.i
.PHONY : framework/ThreadUnsafeLockFreeQueue.cpp.i

framework/ThreadUnsafeLockFreeQueue.s: framework/ThreadUnsafeLockFreeQueue.cpp.s
.PHONY : framework/ThreadUnsafeLockFreeQueue.s

# target to generate assembly for a file
framework/ThreadUnsafeLockFreeQueue.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/framework/ThreadUnsafeLockFreeQueue.cpp.s
.PHONY : framework/ThreadUnsafeLockFreeQueue.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/main.cpp.s
.PHONY : main.cpp.s

test/Timer.o: test/Timer.cpp.o
.PHONY : test/Timer.o

# target to build an object file
test/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/test/Timer.cpp.o
.PHONY : test/Timer.cpp.o

test/Timer.i: test/Timer.cpp.i
.PHONY : test/Timer.i

# target to preprocess a source file
test/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/test/Timer.cpp.i
.PHONY : test/Timer.cpp.i

test/Timer.s: test/Timer.cpp.s
.PHONY : test/Timer.s

# target to generate assembly for a file
test/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/divide_conquer_framework.dir/build.make CMakeFiles/divide_conquer_framework.dir/test/Timer.cpp.s
.PHONY : test/Timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... divide_conquer_framework"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... framework/AbstractProblemSolver.o"
	@echo "... framework/AbstractProblemSolver.i"
	@echo "... framework/AbstractProblemSolver.s"
	@echo "... framework/BaseProblemSolver.o"
	@echo "... framework/BaseProblemSolver.i"
	@echo "... framework/BaseProblemSolver.s"
	@echo "... framework/Framework.o"
	@echo "... framework/Framework.i"
	@echo "... framework/Framework.s"
	@echo "... framework/OmpLock.o"
	@echo "... framework/OmpLock.i"
	@echo "... framework/OmpLock.s"
	@echo "... framework/RandomBucketAccessor.o"
	@echo "... framework/RandomBucketAccessor.i"
	@echo "... framework/RandomBucketAccessor.s"
	@echo "... framework/SharedQueue.o"
	@echo "... framework/SharedQueue.i"
	@echo "... framework/SharedQueue.s"
	@echo "... framework/ThreadStats.o"
	@echo "... framework/ThreadStats.i"
	@echo "... framework/ThreadStats.s"
	@echo "... framework/ThreadUnsafeLockFreeFactory.o"
	@echo "... framework/ThreadUnsafeLockFreeFactory.i"
	@echo "... framework/ThreadUnsafeLockFreeFactory.s"
	@echo "... framework/ThreadUnsafeLockFreeQueue.o"
	@echo "... framework/ThreadUnsafeLockFreeQueue.i"
	@echo "... framework/ThreadUnsafeLockFreeQueue.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test/Timer.o"
	@echo "... test/Timer.i"
	@echo "... test/Timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

